export const GET_PRODUCT = {
    DOING: 'GET_PRODUCT_DOING',
    SUCCESS: 'GET_PRODUCT_SUCCESS',
    FAILURE: 'GET_PRODUCT_FAILURE'
};

export const GET_PRODUCT_BY_ID = {
    DOING: 'GET_PRODUCT_BY_ID_DOING',
    SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
    FAILURE: 'GET_PRODUCT_BY_ID_FAILURE'
};

export const ADD_NEW_PRODUCT = {
    DOING: 'ADD_NEW_PRODUCT_DOING',
    SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
    FAILURE: 'ADD_NEW_PRODUCT_FAILURE'
};

export const UPDATE_PRODUCT = {
    DOING: 'UPDATE_PRODUCT_DOING',
    SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    FAILURE: 'UPDATE_PRODUCT_FAILURE'
};

export const DELETE_PRODUCT = {
    DOING: 'DELETE_PRODUCT_DOING',
    SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    FAILURE: 'DELETE_PRODUCT_FAILURE'
};

export const PRODUCT_DIALOG = {
    SHOW_ADD_NEW_PRODUCT: 'SHOW_ADD_NEW_PRODUCT',
    SHOW_EDIT_PRODUCT: 'SHOW_EDIT_PRODUCT',
    SHOW_DELETE_PRODUCT: 'SHOW_DELETE_PRODUCT'
};

export const ADD_TO_CART = {
    DOING: 'ADD_TO_CART_DOING',
    SUCCESS: 'ADD_TO_CART_SUCCESS',
    FAILURE: 'ADD_TO_CART_FAILURE'
};

export const RELOAD = 'RELOAD';

export const SIGN_UP = {
    DOING: 'SIGN_UP_DOING',
    SUCCESS: 'SIGN_UP_SUCCESS',
    FAILURE: 'SIGN_UP_FAILURE'
};

export const SIGN_IN = {
    DOING: 'SIGN_IN_DOING',
    SUCCESS: 'SIGN_IN_SUCCESS',
    FAILURE: 'SIGN_IN_FAILURE'
};

export const LOCAL_STORAGE = {
    CART: 'cart',
    CURRENT_USER: 'current_user',
    OLD_URL: 'old_url'
};

export const BUTTON_TYPE = {
    OK: 'Ok',
    CANCEL: 'Cancel',
    YES: 'Yes',
    NO: 'No',
    CLOSE: 'Close'
};
